---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myappgcr
 labels:
  app: myappgcr
spec:
 replicas: 2
 selector:
  matchLabels:
   app: myappgcr
 template:
  metadata: 
   labels:
    app: myappgcr
  spec:
   containers:
   - name: myappgcr
     image: gcr.io/devops-san-273920/devops:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myappgcr
spec:
  type: LoadBalancer
  selector:
    app: myappgcr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
